/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFilesIndexRouteImport } from './routes/api/files/index'
import { Route as ApiFilesPutRouteImport } from './routes/api/files/put'
import { Route as ApiFilesListRouteImport } from './routes/api/files/list'
import { Route as ApiFilesGetRouteImport } from './routes/api/files/get'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIndexRoute = ApiFilesIndexRouteImport.update({
  id: '/api/files/',
  path: '/api/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesPutRoute = ApiFilesPutRouteImport.update({
  id: '/api/files/put',
  path: '/api/files/put',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesListRoute = ApiFilesListRouteImport.update({
  id: '/api/files/list',
  path: '/api/files/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesGetRoute = ApiFilesGetRouteImport.update({
  id: '/api/files/get',
  path: '/api/files/get',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/files/get': typeof ApiFilesGetRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/put': typeof ApiFilesPutRoute
  '/api/files/': typeof ApiFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/files/get': typeof ApiFilesGetRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/put': typeof ApiFilesPutRoute
  '/api/files': typeof ApiFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/files/get': typeof ApiFilesGetRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/put': typeof ApiFilesPutRoute
  '/api/files/': typeof ApiFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/files/get'
    | '/api/files/list'
    | '/api/files/put'
    | '/api/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/files/get'
    | '/api/files/list'
    | '/api/files/put'
    | '/api/files'
  id:
    | '__root__'
    | '/'
    | '/api/files/get'
    | '/api/files/list'
    | '/api/files/put'
    | '/api/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFilesGetRoute: typeof ApiFilesGetRoute
  ApiFilesListRoute: typeof ApiFilesListRoute
  ApiFilesPutRoute: typeof ApiFilesPutRoute
  ApiFilesIndexRoute: typeof ApiFilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/': {
      id: '/api/files/'
      path: '/api/files'
      fullPath: '/api/files/'
      preLoaderRoute: typeof ApiFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/put': {
      id: '/api/files/put'
      path: '/api/files/put'
      fullPath: '/api/files/put'
      preLoaderRoute: typeof ApiFilesPutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/list': {
      id: '/api/files/list'
      path: '/api/files/list'
      fullPath: '/api/files/list'
      preLoaderRoute: typeof ApiFilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/get': {
      id: '/api/files/get'
      path: '/api/files/get'
      fullPath: '/api/files/get'
      preLoaderRoute: typeof ApiFilesGetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFilesGetRoute: ApiFilesGetRoute,
  ApiFilesListRoute: ApiFilesListRoute,
  ApiFilesPutRoute: ApiFilesPutRoute,
  ApiFilesIndexRoute: ApiFilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
